apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
namespace: duke-training
images:
- name: asia.gcr.io/poc-innovation-iot/gitlab-runner-example-duke
  newTag: b4426774
